import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
 await page.goto('http://127.0.0.1:3000');await page.getByRole('button',{name:'Open a sample workspace'}).waitFor();
 await page.screenshot({path:'artifacts/login-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Open a sample workspace'}).click();
 await page.getByRole('heading',{name:'Your knowledge, organized.'}).waitFor();
 assert.equal(await page.locator('.faq-card').count(),6);
 await page.screenshot({path:'artifacts/knowledge-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'+ Create FAQ',exact:true}).click();
 await page.getByLabel('Question',{exact:true}).fill('Is there a student discount?');
 await page.getByLabel('Answer',{exact:true}).fill('Students receive a 15 percent discount with a valid college ID.');
 await page.getByLabel('Category',{exact:true}).selectOption('Billing');
 await page.getByRole('button',{name:'Save FAQ'}).click();
 await page.getByRole('heading',{name:'Is there a student discount?'}).waitFor();
 assert.equal(await page.locator('.faq-card').count(),7);
 await page.getByLabel('Filter FAQs').fill('student discount');assert.equal(await page.locator('.faq-card').count(),1);
 await page.getByRole('button',{name:'Edit',exact:true}).click();
 await page.getByLabel('Answer',{exact:true}).fill('Students receive a 20 percent discount with a valid college ID.');
 await page.getByRole('button',{name:'Save FAQ'}).click();
 await page.getByText('Students receive a 20 percent discount with a valid college ID.',{exact:true}).waitFor();
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Delete',exact:true}).click();
 await page.getByRole('heading',{name:'No answers found.'}).waitFor();
 await page.getByLabel('Filter FAQs').fill('');
 await page.getByRole('button',{name:'FAQ studio',exact:false}).first().click();
 await page.getByRole('button',{name:'Use sample content'}).click();
 await page.getByRole('button',{name:'Generate drafts'}).click();
 await page.locator('.draft-card').first().waitFor();assert.ok(await page.locator('.draft-card').count()>=3);
 await page.screenshot({path:'artifacts/studio-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Review & save'}).first().click();
 await page.getByLabel('Question',{exact:true}).fill('What does the sample refund policy say?');
 await page.getByRole('button',{name:'Save FAQ'}).click();
 await page.locator('#faq-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Test assistant'}).click();
 await page.getByLabel('Your question').fill('How can I get my money back?');
 await page.getByRole('button',{name:'Send question'}).click();
 await page.locator('.source-link').first().waitFor();
 assert.match(await page.locator('.message').last().innerText(),/14 days/);
 await page.screenshot({path:'artifacts/assistant-desktop.png',fullPage:true});
 await page.getByLabel('Your question').fill('Tell me about quantum asteroid telescopes.');
 await page.getByRole('button',{name:'Send question'}).click();
 await page.getByText('I could not find a reliable answer in your knowledge base.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Knowledge base'}).click();
 await page.reload();await page.getByRole('heading',{name:'Your knowledge, organized.'}).waitFor();
 assert.equal(await page.locator('.faq-card').count(),7);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/knowledge-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 await page.getByRole('button',{name:'Sign out',exact:true}).last().click();
 await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('PASS: desktop and mobile UI, demo login, create, edit, delete, filter, generation, draft review, chat with sources, unknown questions, session reload, logout; no JS errors or mobile overflow.');
}finally{await browser.close();}

